### ISSUE TITLE
Confusion about the usage of the term COFF

### ISSUE THREAD

**Issue by iddev5** [kubkon/zld#3]
Hello,

I am a bit confused about the usage of the term COFF in zld. This is related to the fact that the COFF backend is being targeted at windows and that PE is the format which is actually used on windows and COFF is an extension of PE.

So, in short why does zld use the term COFF and not PE? The only hint of PE is in Readme. Afaik, COFF was supposed to be a unix format, while PE be the windows/uefi format.

Apologies if this is not the right time/place to ask the question.

Thank you.

**Comment by kubkon** [comment]
Hi @iddev5! Actually, it's the other way around: PE is an extension of COFF. To be honest, I don't really have a reason for using COFF instead of PE in this instance other than following Zig's self-hosted convention. I'm happy to reconsider naming but I think this can be delayed until we actually have something to show for, wouldn't you agree? :-)

**Comment by iddev5** [comment]
> other way around
Oh right true, my brain accidentally interchanged them :p 

> wouldn't you agree?
I agree. My only reason for asking was to gain any technical insight (if any) behind this decision.

Thanks for explaining.
